# Generated by Django 5.2.8 on 2025-11-21 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RockArtCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="RockArtType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("site_number", models.CharField(max_length=64, unique=True)),
                ("date_recorded", models.DateField(blank=True, null=True)),
                ("project_name", models.CharField(blank=True, max_length=255)),
                ("project_description", models.TextField(blank=True)),
                (
                    "recorders",
                    models.CharField(
                        blank=True,
                        help_text="Names of recorder(s) as entered on the form.",
                        max_length=255,
                    ),
                ),
                (
                    "temporary_housing",
                    models.CharField(
                        blank=True, help_text="Temporary data housing.", max_length=255
                    ),
                ),
                (
                    "permanent_housing",
                    models.CharField(
                        blank=True,
                        help_text="Permanent data housing (e.g. TARL).",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RockArtNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("author", models.CharField(blank=True, max_length=128)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("site_narrative", "Site Narrative"),
                            ("iconographic_inventory", "Iconographic Inventory"),
                            ("daily_recorder", "Daily Recorder"),
                        ],
                        default="site_narrative",
                        max_length=32,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("field", "Field"), ("lab", "Lab")],
                        default="field",
                        max_length=16,
                    ),
                ),
                ("text", models.TextField()),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="rockart.site",
                    ),
                ),
            ],
            options={
                "ordering": ["site", "date", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="RockArtInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reason_for_visit", models.TextField(blank=True)),
                ("previously_recorded", models.BooleanField(default=False)),
                ("previous_record_details", models.TextField(blank=True)),
                (
                    "location_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("unknown", "Unknown"),
                            ("rock_shelter", "Rock shelter"),
                            ("cave", "Cave"),
                            ("open_air", "Open air"),
                            ("other", "Other"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                (
                    "radiocarbon_assay",
                    models.CharField(
                        blank=True, help_text="Assay number or 'None'.", max_length=64
                    ),
                ),
                ("radiocarbon_citation", models.TextField(blank=True)),
                (
                    "unidentified_description",
                    models.TextField(
                        blank=True,
                        help_text="Description if category is 'Unidentified'.",
                    ),
                ),
                ("best_winter", models.CharField(blank=True, max_length=64)),
                ("best_spring", models.CharField(blank=True, max_length=64)),
                ("best_summer", models.CharField(blank=True, max_length=64)),
                ("best_fall", models.CharField(blank=True, max_length=64)),
                (
                    "engraving_technique",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "None"),
                            ("pecked", "Pecked"),
                            ("incised", "Incised"),
                            ("polished", "Polished"),
                            ("other", "Other"),
                        ],
                        default="none",
                        max_length=32,
                    ),
                ),
                ("engraving_other", models.CharField(blank=True, max_length=128)),
                (
                    "painting_technique",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "None"),
                            ("wet_applied", "Wet-applied"),
                            ("dry_applied", "Dry-applied"),
                            ("finger_painted", "Finger-painted"),
                            ("stenciled", "Stenciled"),
                            ("blown", "Blown"),
                            ("splatter", "Splatter"),
                            ("other", "Other"),
                        ],
                        default="none",
                        max_length=32,
                    ),
                ),
                ("painting_other", models.CharField(blank=True, max_length=128)),
                (
                    "rock_art_categories",
                    models.ManyToManyField(
                        blank=True, related_name="sites", to="rockart.rockartcategory"
                    ),
                ),
                (
                    "rock_art_types",
                    models.ManyToManyField(
                        blank=True, related_name="sites", to="rockart.rockarttype"
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rock_art",
                        to="rockart.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RockArtCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("repainting", models.CharField(blank=True, max_length=128)),
                ("repainting_comments", models.TextField(blank=True)),
                ("revarnishing", models.CharField(blank=True, max_length=128)),
                ("revarnishing_comments", models.TextField(blank=True)),
                (
                    "clarity_overall",
                    models.CharField(
                        blank=True,
                        help_text="Clarity of art (overall).",
                        max_length=128,
                    ),
                ),
                ("physical_agent", models.CharField(blank=True, max_length=128)),
                ("physical_notes", models.TextField(blank=True)),
                ("chemical_agent", models.CharField(blank=True, max_length=128)),
                ("chemical_notes", models.TextField(blank=True)),
                ("biochemical_agent", models.CharField(blank=True, max_length=128)),
                ("biochemical_notes", models.TextField(blank=True)),
                ("human_impacts", models.CharField(blank=True, max_length=128)),
                ("human_impacts_notes", models.TextField(blank=True)),
                ("animal_impacts", models.CharField(blank=True, max_length=128)),
                ("animal_impacts_notes", models.TextField(blank=True)),
                ("known_or_perceived_future_impacts", models.TextField(blank=True)),
                ("future_research_potential", models.TextField(blank=True)),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="rockart.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RockArtAttributes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("style_description", models.TextField(blank=True)),
                ("post_pecking", models.CharField(blank=True, max_length=128)),
                ("post_abrading", models.CharField(blank=True, max_length=128)),
                ("post_incising", models.CharField(blank=True, max_length=128)),
                ("post_additional_comments", models.TextField(blank=True)),
                (
                    "incorporation",
                    models.CharField(
                        blank=True,
                        help_text="E.g. use of natural features.",
                        max_length=128,
                    ),
                ),
                (
                    "scaffolding_required",
                    models.CharField(
                        blank=True,
                        help_text="Yes/No/Unknown as recorded.",
                        max_length=64,
                    ),
                ),
                ("potential_for_c14", models.CharField(blank=True, max_length=64)),
                ("general_comments", models.TextField(blank=True)),
                ("has_black", models.BooleanField(default=False)),
                ("has_red", models.BooleanField(default=False)),
                ("has_yellow", models.BooleanField(default=False)),
                ("has_white", models.BooleanField(default=False)),
                ("other_colors", models.CharField(blank=True, max_length=255)),
                (
                    "rock_art_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attribute_sets",
                        to="rockart.rockartcategory",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="rockart.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PhotogrammetryLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                (
                    "photo_type",
                    models.CharField(
                        choices=[
                            ("sfm", "SfM"),
                            ("gigapan", "Gigapan"),
                            ("other", "Other"),
                        ],
                        default="sfm",
                        max_length=16,
                    ),
                ),
                (
                    "photo_range",
                    models.CharField(
                        blank=True,
                        help_text="Photo number range or identifier.",
                        max_length=128,
                    ),
                ),
                ("scale_used", models.CharField(blank=True, max_length=128)),
                ("description", models.TextField(blank=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photogrammetry_logs",
                        to="rockart.site",
                    ),
                ),
            ],
            options={
                "ordering": ["site", "date"],
            },
        ),
        migrations.CreateModel(
            name="GeneralIconographicAttributes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("antlers_with_dots", models.PositiveIntegerField(default=0)),
                ("speech_breath", models.PositiveIntegerField(default=0)),
                ("large_cluster_single_motif", models.PositiveIntegerField(default=0)),
                ("half_bodied_figures", models.PositiveIntegerField(default=0)),
                ("full_bodied_figures", models.PositiveIntegerField(default=0)),
                ("dismembered_figures", models.PositiveIntegerField(default=0)),
                (
                    "procession_of_anthropomorphs",
                    models.PositiveIntegerField(default=0),
                ),
                ("procession_of_zoomorphs", models.PositiveIntegerField(default=0)),
                ("peyotism_motif", models.PositiveIntegerField(default=0)),
                ("otherworld_journey_motif", models.PositiveIntegerField(default=0)),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="general_iconographic_attributes",
                        to="rockart.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EnigmaticInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("box_with_legs", models.PositiveIntegerField(default=0)),
                ("arch_with_portal", models.PositiveIntegerField(default=0)),
                ("crenelated_box", models.PositiveIntegerField(default=0)),
                ("comb_shape", models.PositiveIntegerField(default=0)),
                ("grid", models.PositiveIntegerField(default=0)),
                ("zig_zag_line", models.PositiveIntegerField(default=0)),
                ("spiral", models.PositiveIntegerField(default=0)),
                ("serpentine_lines", models.PositiveIntegerField(default=0)),
                ("other_enigmatics", models.PositiveIntegerField(default=0)),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enigmatic_inventory",
                        to="rockart.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AnthropomorphInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("frontal", models.PositiveIntegerField(default=0)),
                ("profile", models.PositiveIntegerField(default=0)),
                ("upside_down", models.PositiveIntegerField(default=0)),
                ("horizontal", models.PositiveIntegerField(default=0)),
                ("impaled_anthropomorph", models.PositiveIntegerField(default=0)),
                ("centralstyling", models.PositiveIntegerField(default=0)),
                ("non_centralstyled", models.PositiveIntegerField(default=0)),
                ("headshape_round", models.PositiveIntegerField(default=0)),
                ("headshape_square", models.PositiveIntegerField(default=0)),
                ("headshape_u_shape", models.PositiveIntegerField(default=0)),
                ("headshape_other", models.PositiveIntegerField(default=0)),
                ("arms_extended_up", models.PositiveIntegerField(default=0)),
                ("arms_extended_down", models.PositiveIntegerField(default=0)),
                ("right_handed", models.PositiveIntegerField(default=0)),
                ("left_handed", models.PositiveIntegerField(default=0)),
                ("headdress", models.PositiveIntegerField(default=0)),
                ("mask", models.PositiveIntegerField(default=0)),
                ("staff", models.PositiveIntegerField(default=0)),
                ("rabbit_stick", models.PositiveIntegerField(default=0)),
                ("other_paraphernalia", models.PositiveIntegerField(default=0)),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anthropomorph_inventory",
                        to="rockart.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ZoomorphInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("feline", models.PositiveIntegerField(default=0)),
                ("avian", models.PositiveIntegerField(default=0)),
                ("snakes", models.PositiveIntegerField(default=0)),
                ("antlered_deer", models.PositiveIntegerField(default=0)),
                ("deer_without_antlers", models.PositiveIntegerField(default=0)),
                ("other_zoomorphs", models.PositiveIntegerField(default=0)),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zoomorph_inventory",
                        to="rockart.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Panel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("panel_number", models.PositiveIntegerField()),
                (
                    "overall_shelter_orientation",
                    models.CharField(
                        blank=True,
                        help_text="Cardinal orientation, degrees, etc.",
                        max_length=64,
                    ),
                ),
                ("height_m", models.FloatField(default=0.0)),
                ("width_m", models.FloatField(default=0.0)),
                ("area_m2", models.FloatField(default=0.0)),
                (
                    "exposure_degrees",
                    models.FloatField(
                        default=0.0,
                        help_text="Panel exposure in degrees as recorded on form.",
                    ),
                ),
                ("anthropomorphs_initial", models.PositiveIntegerField(default=0)),
                ("anthropomorphs_final", models.PositiveIntegerField(default=0)),
                ("enigmatics_initial", models.PositiveIntegerField(default=0)),
                ("enigmatics_final", models.PositiveIntegerField(default=0)),
                ("zoomorphs_initial", models.PositiveIntegerField(default=0)),
                ("zoomorphs_final", models.PositiveIntegerField(default=0)),
                ("graffiti_initial", models.PositiveIntegerField(default=0)),
                ("graffiti_final", models.PositiveIntegerField(default=0)),
                ("remnant_initial", models.PositiveIntegerField(default=0)),
                ("remnant_final", models.PositiveIntegerField(default=0)),
                ("unclassified_initial", models.PositiveIntegerField(default=0)),
                ("unclassified_final", models.PositiveIntegerField(default=0)),
                ("figurative_petros_initial", models.PositiveIntegerField(default=0)),
                ("figurative_petros_final", models.PositiveIntegerField(default=0)),
                ("grooves_initial", models.PositiveIntegerField(default=0)),
                ("grooves_final", models.PositiveIntegerField(default=0)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="panels",
                        to="rockart.site",
                    ),
                ),
            ],
            options={
                "unique_together": {("site", "panel_number")},
            },
        ),
    ]
